### ISSUE TITLE
Organization and Cleanup

### ISSUE THREAD

**Issue by sijad** [eribertomota/axel#4]
* [x] Move `.h` `.c` files to `src` folder
* [x] Move `.po` files to `i18n` folder
* [x] Rename `README.to-contribute` to `CONTRIBUTING.md`, [why?](https://github.com/blog/1184-contributing-guidelines)
* [ ] Rename `COPYING` to `LICENSE`
* [ ] remove `ROADMAP` and use Github's [Milestones](https://github.com/eribertomota/axel/milestones) instead
* [ ] remove all text files (API, UPDATE-CHECK, ...) and use Github's [Wiki](https://github.com/eribertomota/axel/wiki) instead
* [x] add `.gitignore`

Things I'm not sure about:
* Update license to v3
* Use a `dev` branch
* update license in `.h` `.c` header
* remove `CHANGES` and use Github's release describe instead

**I'll complete this list**

**Comment by eribertomota** [comment]
Some itens already being done in autotools branch.

**Comment by sijad** [comment]
sorry I didn't see that, which branch should I work on?

**Comment by eribertomota** [comment]
I suggest you clone the repository and send a patch or fork the repository and create a branch.

I will try finish the autotools in this weekend.

**Comment by sdt** [comment]
There is a .gitignore included in PR #10

**Comment by denji** [comment]
Create organization https://github.com/axel-dl

 - Owned @appaji (Giridhar Yasa) 
 - Owned @eribertomota (Joao Eriberto Mota Filho)
 - Owned @phihag (Philipp Hagemeister)

The reason for creation was to restore the code of the project: `unicode-progressbar`, `reactivation`, `no-clobber`, `cookies`, `content-disposition`, `https` back-ported code @emiraga https://github.com/axel-dl/axel-ideas/branches ([README.md](https://github.com/axel-dl/axel-ideas/blob/master/README.md)).

Ready to leave organization.

**Comment by eribertomota** [comment]
Hi,

Why you don't join to current project? Several changes and improvements
were made...

Eriberto


2016-05-28 17:27 GMT-03:00 Denis Denisov <notifications@github.com>:

**Comment by eribertomota** [comment]
Hi,

Thanks for all suggestions.

I intent to close this bug in 15 days if there are no objections.

My considerations:

1.  Rename COPYING to LICENSE

The program uses GPL-2+ license (migrating to GPL-2+ with OpenSSL exception). Is a common practice this file be named as COPYING.

2. Remove ROADMAP and use Github's Milestones instead; Remove all text files (API, UPDATE-CHECK, ...) and use Github's Wiki instead.

I think that the final user must have access to these documents via source code (web sites aren't full compliant with Free Software because the people that haven't Internet will be discriminated; please, read more here[1]). All files moved to doc/ directory.

[1] https://people.debian.org/~bap/dfsg-faq.html#desert_island

3. Update license to v3

Not possible without a permission from all previous authors. Recently, they already agreed to change to GPL-2+ with OpenSSL exception. 

4. Use a dev branch

Using tags for last release and pull requests method.

5. Remove CHANGES and use Github's release describe instead

Users will be benefited by a local ChangeLog.

6. Requests that was fulfilled:

- Move .h .c files to src folder.
- Move .po files to i18n folder. (was used po folder)
- Rename README.to-contribute to CONTRIBUTING.md.
- Add .gitignore.
- Update license in .h .c header.

Regards,

Eriberto

**Comment by eribertomota** [comment]
Closing. Thanks!
